apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-replicaset
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: '600790893911.dkr.ecr.us-east-1.amazonaws.com/assgnmt2mysql_images:v0.2'
        ports:
        - containerPort: 3306
