apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
    component: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
<<<<<<< HEAD
    app: mysql
=======
    app: mysql
>>>>>>> 64f6fb9fc3cd94a5538e9b761defc0d4767f92e8
