apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-replicaset
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: '600790893911.dkr.ecr.us-east-1.amazonaws.com/assgnmt2webapp_images:v0.2'
        ports:
        - containerPort: 80
      env:
        - name: DB_HOST
          value: "mysql"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root""
        - name: DATABASE
          value: "employees"
        - name: APP_COLOR
          value: lime
        - name: MYSQL_ROOT_PASSWORD
          value: "ZXItc2VjcmV0LXBhc3N3b2Q="