apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: webapp
        image: "600790893911.dkr.ecr.us-east-1.amazonaws.com/assgnmt2webapp_images:v0.2"
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "mysql"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root""
        - name: DATABASE
          value: "employees"
        - name: APP_COLOR
          value: lime
        - name: MYSQL_ROOT_PASSWORD
          value: "ZXItc2VjcmV0LXBhc3N3b2Q="
  ---
  apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: employees
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30000