apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
  - name: webapp-serviceimg
    image: 600790893911.dkr.ecr.us-east-1.amazonaws.com/assgnmt2webapp_images:v0.2
    env:
      - name: DBPWD
        value: ZXItc2VjcmV0LXBhc3N3b2Q=
      - name: DBUSER
        value: root
      - name: DBHOST
        value: "mysql.database.svc.cluster.local"
      - name: DBPORT
        value: "3306"
      - name: APP_COLOR
        value: "lime"
    ports:
      - containerPort: 8080
